modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"

[[mods]] #mandatory
modId="sotscompanion" #mandatory
version="${file.jarVersion}" #mandatory
displayName="SotS companion mod" #mandatory
authors="Love, Cheese and small house plants" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Companion mod for Sons of the Sand modpack.

Mostly used for compatibility issues between Atum and its intefconnections with other mods and vanilla.
'''
[[dependencies.sotscompanion]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"

# Here's another dependency
[[dependencies.sotscompanion]]
    modId="atum" #mandatory
    mandatory=true #mandatory
    versionRange="[1.16.5-2.2.5,)" #mandatory
    ordering="AFTER"
    side="BOTH"
